#!/bin/sh
# Creating devices
# mknod -m 622 dev/console c 5 1
# mknod -m 666 dev/null c 1 3
# mknod -m 666 /dev/tty c 5 0

# Mounting Virtual Filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t debugfs debugfs /sys/kernel/debug

# Add atkbd.c to debug control
echo 'file atkbd.c +p' > /sys/kernel/debug/dynamic_debug/control

exec /bin/sh
