#!/bin/sh
# Creating devices
# mknod -m 622 dev/console c 5 1
# mknod -m 666 dev/null c 1 3
# mknod -m 666 /dev/tty c 5 0

# Mounting Virtual Filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

exec /bin/sh
